SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
CREATE TABLE `usernote` (
  `noteID` int(11) NOT NULL,
 
  
  `title` varchar(60) NOT NULL,
  `noteBody` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `usernote`
  ADD PRIMARY KEY (`noteID`);

ALTER TABLE `usernote`
  MODIFY `noteID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

